const countries = 
[
    { dialCode: "+91", flag: "https://flagcdn.com/in.svg", alpha2: "IN", name: "India" },
    { dialCode: "+7", flag: "https://flagcdn.com/ru.svg", alpha2: "RU", name: "Russia" },
    { dialCode: "+7", flag: "https://flagcdn.com/kz.svg", alpha2: "KZ", name: "Kazakhstan" },
    { dialCode: "+81", flag: "https://flagcdn.com/jp.svg", alpha2: "JP", name: "Japan" },
    { dialCode: "+82", flag: "https://flagcdn.com/kr.svg", alpha2: "KR", name: "South Korea" },
    { dialCode: "+84", flag: "https://flagcdn.com/vn.svg", alpha2: "VN", name: "Vietnam" },
    { dialCode: "+850", flag: "https://flagcdn.com/kp.svg", alpha2: "KP", name: "North Korea" },
    { dialCode: "+852", flag: "https://flagcdn.com/hk.svg", alpha2: "HK", name: "Hong Kong" },
    { dialCode: "+853", flag: "https://flagcdn.com/mo.svg", alpha2: "MO", name: "Macau" },
    { dialCode: "+855", flag: "https://flagcdn.com/kh.svg", alpha2: "KH", name: "Cambodia" },
    { dialCode: "+856", flag: "https://flagcdn.com/la.svg", alpha2: "LA", name: "Laos" },
    { dialCode: "+86", flag: "https://flagcdn.com/cn.svg", alpha2: "CN", name: "China" },
    { dialCode: "+880", flag: "https://flagcdn.com/bd.svg", alpha2: "BD", name: "Bangladesh" },
    { dialCode: "+886", flag: "https://flagcdn.com/tw.svg", alpha2: "TW", name: "Taiwan" },
    { dialCode: "+90", flag: "https://flagcdn.com/tr.svg", alpha2: "TR", name: "Turkey" },
    { dialCode: "+92", flag: "https://flagcdn.com/pk.svg", alpha2: "PK", name: "Pakistan" },
    { dialCode: "+93", flag: "https://flagcdn.com/af.svg", alpha2: "AF", name: "Afghanistan" },
    { dialCode: "+94", flag: "https://flagcdn.com/lk.svg", alpha2: "LK", name: "Sri Lanka" },
    { dialCode: "+95", flag: "https://flagcdn.com/mm.svg", alpha2: "MM", name: "Myanmar" },
    { dialCode: "+960", flag: "https://flagcdn.com/mv.svg", alpha2: "MV", name: "Maldives" },
    { dialCode: "+1", flag: "https://flagcdn.com/ca.svg", alpha2: "CA", name: "Canada" },
    { dialCode: "+1", flag: "https://flagcdn.com/us.svg", alpha2: "US", name: "United States" },
    { dialCode: "+1242", flag: "https://flagcdn.com/bs.svg", alpha2: "BS", name: "Bahamas" },
    { dialCode: "+1246", flag: "https://flagcdn.com/bb.svg", alpha2: "BB", name: "Barbados" },
    { dialCode: "+1264", flag: "https://flagcdn.com/ai.svg", alpha2: "AI", name: "Anguilla" },
    { dialCode: "+1268", flag: "https://flagcdn.com/ag.svg", alpha2: "AG", name: "Antigua and Barbuda" },
    { dialCode: "+1284", flag: "https://flagcdn.com/vg.svg", alpha2: "VG", name: "Virgin Islands, British" },
    { dialCode: "+1340", flag: "https://flagcdn.com/vi.svg", alpha2: "VI", name: "Virgin Islands, U.S." },
    { dialCode: "+1441", flag: "https://flagcdn.com/bm.svg", alpha2: "BM", name: "Bermuda" },
    { dialCode: "+1473", flag: "https://flagcdn.com/gd.svg", alpha2: "GD", name: "Grenada" },
    { dialCode: "+1649", flag: "https://flagcdn.com/tc.svg", alpha2: "TC", name: "Turks and Caicos Islands" },
    { dialCode: "+1664", flag: "https://flagcdn.com/ms.svg", alpha2: "MS", name: "Montserrat" },
    { dialCode: "+1670", flag: "https://flagcdn.com/mp.svg", alpha2: "MP", name: "Northern Mariana Islands" },
    { dialCode: "+1671", flag: "https://flagcdn.com/gu.svg", alpha2: "GU", name: "Guam" },
    { dialCode: "+1684", flag: "https://flagcdn.com/as.svg", alpha2: "AS", name: "American Samoa" },
    { dialCode: "+1758", flag: "https://flagcdn.com/lc.svg", alpha2: "LC", name: "Saint Lucia" },
    { dialCode: "+1767", flag: "https://flagcdn.com/dm.svg", alpha2: "DM", name: "Dominica" },
    { dialCode: "+1784", flag: "https://flagcdn.com/vc.svg", alpha2: "VC", name: "Saint Vincent and the Grenadines" },
    { dialCode: "+1849", flag: "https://flagcdn.com/do.svg", alpha2: "DO", name: "Dominican Republic" },
    { dialCode: "+1868", flag: "https://flagcdn.com/tt.svg", alpha2: "TT", name: "Trinidad and Tobago" },
    { dialCode: "+1869", flag: "https://flagcdn.com/kn.svg", alpha2: "KN", name: "Saint Kitts and Nevis" },
    { dialCode: "+1876", flag: "https://flagcdn.com/jm.svg", alpha2: "JM", name: "Jamaica" },
    { dialCode: "+1939", flag: "https://flagcdn.com/pr.svg", alpha2: "PR", name: "Puerto Rico" },
    { dialCode: "+20", flag: "https://flagcdn.com/eg.svg", alpha2: "EG", name: "Egypt" },
    { dialCode: "+211", flag: "https://flagcdn.com/ss.svg", alpha2: "SS", name: "South Sudan" },
    { dialCode: "+212", flag: "https://flagcdn.com/ma.svg", alpha2: "MA", name: "Morocco" },
    { dialCode: "+213", flag: "https://flagcdn.com/dz.svg", alpha2: "DZ", name: "Algeria" },
    { dialCode: "+216", flag: "https://flagcdn.com/tn.svg", alpha2: "TN", name: "Tunisia" },
    { dialCode: "+218", flag: "https://flagcdn.com/ly.svg", alpha2: "LY", name: "Libya" },
    { dialCode: "+220", flag: "https://flagcdn.com/gm.svg", alpha2: "GM", name: "Gambia" },
    { dialCode: "+221", flag: "https://flagcdn.com/sn.svg", alpha2: "SN", name: "Senegal" },
    { dialCode: "+222", flag: "https://flagcdn.com/mr.svg", alpha2: "MR", name: "Mauritania" },
    { dialCode: "+223", flag: "https://flagcdn.com/ml.svg", alpha2: "ML", name: "Mali" },
    { dialCode: "+224", flag: "https://flagcdn.com/gn.svg", alpha2: "GN", name: "Guinea" },
    { dialCode: "+225", flag: "https://flagcdn.com/ci.svg", alpha2: "CI", name: "Cote d'Ivoire" },
    { dialCode: "+226", flag: "https://flagcdn.com/bf.svg", alpha2: "BF", name: "Burkina Faso" },
    { dialCode: "+227", flag: "https://flagcdn.com/ne.svg", alpha2: "NE", name: "Niger" },
    { dialCode: "+228", flag: "https://flagcdn.com/tg.svg", alpha2: "TG", name: "Togo" },
    { dialCode: "+229", flag: "https://flagcdn.com/bj.svg", alpha2: "BJ", name: "Benin" },
    { dialCode: "+230", flag: "https://flagcdn.com/mu.svg", alpha2: "MU", name: "Mauritius" },
    { dialCode: "+231", flag: "https://flagcdn.com/lr.svg", alpha2: "LR", name: "Liberia" },
    { dialCode: "+232", flag: "https://flagcdn.com/sl.svg", alpha2: "SL", name: "Sierra Leone" },
    { dialCode: "+233", flag: "https://flagcdn.com/gh.svg", alpha2: "GH", name: "Ghana" },
    { dialCode: "+234", flag: "https://flagcdn.com/ng.svg", alpha2: "NG", name: "Nigeria" },
    { dialCode: "+235", flag: "https://flagcdn.com/td.svg", alpha2: "TD", name: "Chad" },
    { dialCode: "+236", flag: "https://flagcdn.com/cf.svg", alpha2: "CF", name: "Central African Republic" },
    { dialCode: "+237", flag: "https://flagcdn.com/cm.svg", alpha2: "CM", name: "Cameroon" },
    { dialCode: "+238", flag: "https://flagcdn.com/cv.svg", alpha2: "CV", name: "Cape Verde" },
    { dialCode: "+239", flag: "https://flagcdn.com/st.svg", alpha2: "ST", name: "Sao Tome and Principe" },
    { dialCode: "+240", flag: "https://flagcdn.com/gq.svg", alpha2: "GQ", name: "Equatorial Guinea" },
    { dialCode: "+241", flag: "https://flagcdn.com/ga.svg", alpha2: "GA", name: "Gabon" },
    { dialCode: "+242", flag: "https://flagcdn.com/cg.svg", alpha2: "CG", name: "Congo" },
    { dialCode: "+243", flag: "https://flagcdn.com/cd.svg", alpha2: "CD", name: "DR Congo" },
    { dialCode: "+244", flag: "https://flagcdn.com/ao.svg", alpha2: "AO", name: "Angola" },
    { dialCode: "+245", flag: "https://flagcdn.com/gw.svg", alpha2: "GW", name: "Guinea-Bissau" },
    { dialCode: "+246", flag: "https://flagcdn.com/io.svg", alpha2: "IO", name: "BIOT" },
    { dialCode: "+248", flag: "https://flagcdn.com/sc.svg", alpha2: "SC", name: "Seychelles" },
    { dialCode: "+249", flag: "https://flagcdn.com/sd.svg", alpha2: "SD", name: "Sudan" },
    { dialCode: "+250", flag: "https://flagcdn.com/rw.svg", alpha2: "RW", name: "Rwanda" },
    { dialCode: "+251", flag: "https://flagcdn.com/et.svg", alpha2: "ET", name: "Ethiopia" },
    { dialCode: "+252", flag: "https://flagcdn.com/so.svg", alpha2: "SO", name: "Somalia" },
    { dialCode: "+253", flag: "https://flagcdn.com/dj.svg", alpha2: "DJ", name: "Djibouti" },
    { dialCode: "+254", flag: "https://flagcdn.com/ke.svg", alpha2: "KE", name: "Kenya" },
    { dialCode: "+255", flag: "https://flagcdn.com/tz.svg", alpha2: "TZ", name: "Tanzania" },
    { dialCode: "+256", flag: "https://flagcdn.com/ug.svg", alpha2: "UG", name: "Uganda" },
    { dialCode: "+257", flag: "https://flagcdn.com/bi.svg", alpha2: "BI", name: "Burundi" },
    { dialCode: "+258", flag: "https://flagcdn.com/mz.svg", alpha2: "MZ", name: "Mozambique" },
    { dialCode: "+260", flag: "https://flagcdn.com/zm.svg", alpha2: "ZM", name: "Zambia" },
    { dialCode: "+261", flag: "https://flagcdn.com/mg.svg", alpha2: "MG", name: "Madagascar" },
    { dialCode: "+262", flag: "https://flagcdn.com/yt.svg", alpha2: "YT", name: "Mayotte" },
    { dialCode: "+262", flag: "https://flagcdn.com/re.svg", alpha2: "RE", name: "Reunion" },
    { dialCode: "+263", flag: "https://flagcdn.com/zw.svg", alpha2: "ZW", name: "Zimbabwe" },
    { dialCode: "+264", flag: "https://flagcdn.com/na.svg", alpha2: "NA", name: "Namibia" },
    { dialCode: "+265", flag: "https://flagcdn.com/mw.svg", alpha2: "MW", name: "Malawi" },
    { dialCode: "+266", flag: "https://flagcdn.com/ls.svg", alpha2: "LS", name: "Lesotho" },
    { dialCode: "+267", flag: "https://flagcdn.com/bw.svg", alpha2: "BW", name: "Botswana" },
    { dialCode: "+268", flag: "https://flagcdn.com/sz.svg", alpha2: "SZ", name: "Swaziland" },
    { dialCode: "+269", flag: "https://flagcdn.com/km.svg", alpha2: "KM", name: "Comoros" },
    { dialCode: "+27", flag: "https://flagcdn.com/za.svg", alpha2: "ZA", name: "South Africa" },
    { dialCode: "+290", flag: "https://flagcdn.com/sh.svg", alpha2: "SH", name: "Saint Helena" },
    { dialCode: "+291", flag: "https://flagcdn.com/er.svg", alpha2: "ER", name: "Eritrea" },
    { dialCode: "+297", flag: "https://flagcdn.com/aw.svg", alpha2: "AW", name: "Aruba" },
    { dialCode: "+298", flag: "https://flagcdn.com/fo.svg", alpha2: "FO", name: "Faroe Islands" },
    { dialCode: "+299", flag: "https://flagcdn.com/gl.svg", alpha2: "GL", name: "Greenland" },
    { dialCode: "+30", flag: "https://flagcdn.com/gr.svg", alpha2: "GR", name: "Greece" },
    { dialCode: "+31", flag: "https://flagcdn.com/nl.svg", alpha2: "NL", name: "Netherlands" },
    { dialCode: "+32", flag: "https://flagcdn.com/be.svg", alpha2: "BE", name: "Belgium" },
    { dialCode: "+33", flag: "https://flagcdn.com/fr.svg", alpha2: "FR", name: "France" },
    { dialCode: "+34", flag: "https://flagcdn.com/es.svg", alpha2: "ES", name: "Spain" },
    { dialCode: "+350", flag: "https://flagcdn.com/gi.svg", alpha2: "GI", name: "Gibraltar" },
    { dialCode: "+351", flag: "https://flagcdn.com/pt.svg", alpha2: "PT", name: "Portugal" },
    { dialCode: "+352", flag: "https://flagcdn.com/lu.svg", alpha2: "LU", name: "Luxembourg" },
    { dialCode: "+353", flag: "https://flagcdn.com/ie.svg", alpha2: "IE", name: "Ireland" },
    { dialCode: "+354", flag: "https://flagcdn.com/is.svg", alpha2: "IS", name: "Iceland" },
    { dialCode: "+355", flag: "https://flagcdn.com/al.svg", alpha2: "AL", name: "Albania" },
    { dialCode: "+356", flag: "https://flagcdn.com/mt.svg", alpha2: "MT", name: "Malta" },
    { dialCode: "+357", flag: "https://flagcdn.com/cy.svg", alpha2: "CY", name: "Cyprus" },
    { dialCode: "+358", flag: "https://flagcdn.com/fi.svg", alpha2: "FI", name: "Finland" },
    { dialCode: "+359", flag: "https://flagcdn.com/bg.svg", alpha2: "BG", name: "Bulgaria" },
    { dialCode: "+36", flag: "https://flagcdn.com/hu.svg", alpha2: "HU", name: "Hungary" },
    { dialCode: "+370", flag: "https://flagcdn.com/lt.svg", alpha2: "LT", name: "Lithuania" },
    { dialCode: "+371", flag: "https://flagcdn.com/lv.svg", alpha2: "LV", name: "Latvia" },
    { dialCode: "+372", flag: "https://flagcdn.com/ee.svg", alpha2: "EE", name: "Estonia" },
    { dialCode: "+373", flag: "https://flagcdn.com/md.svg", alpha2: "MD", name: "Moldova" },
    { dialCode: "+374", flag: "https://flagcdn.com/am.svg", alpha2: "AM", name: "Armenia" },
    { dialCode: "+375", flag: "https://flagcdn.com/by.svg", alpha2: "BY", name: "Belarus" },
    { dialCode: "+376", flag: "https://flagcdn.com/ad.svg", alpha2: "AD", name: "Andorra" },
    { dialCode: "+377", flag: "https://flagcdn.com/mc.svg", alpha2: "MC", name: "Monaco" },
    { dialCode: "+378", flag: "https://flagcdn.com/sm.svg", alpha2: "SM", name: "San Marino" },
    { dialCode: "+380", flag: "https://flagcdn.com/ua.svg", alpha2: "UA", name: "Ukraine" },
    { dialCode: "+381", flag: "https://flagcdn.com/rs.svg", alpha2: "RS", name: "Serbia" },
    { dialCode: "+382", flag: "https://flagcdn.com/me.svg", alpha2: "ME", name: "Montenegro" },
    { dialCode: "+383", flag: "https://flagcdn.com/xk.svg", alpha2: "XK", name: "Kosovo" },
    { dialCode: "+385", flag: "https://flagcdn.com/hr.svg", alpha2: "HR", name: "Croatia" },
    { dialCode: "+386", flag: "https://flagcdn.com/si.svg", alpha2: "SI", name: "Slovenia" },
    { dialCode: "+387", flag: "https://flagcdn.com/ba.svg", alpha2: "BA", name: "Bosnia" },
    { dialCode: "+389", flag: "https://flagcdn.com/mk.svg", alpha2: "MK", name: "North Macedonia" },
    { dialCode: "+39", flag: "https://flagcdn.com/it.svg", alpha2: "IT", name: "Italy" },
    { dialCode: "+40", flag: "https://flagcdn.com/ro.svg", alpha2: "RO", name: "Romania" },
    { dialCode: "+41", flag: "https://flagcdn.com/ch.svg", alpha2: "CH", name: "Switzerland" },
    { dialCode: "+420", flag: "https://flagcdn.com/cz.svg", alpha2: "CZ", name: "Czech Republic" },
    { dialCode: "+421", flag: "https://flagcdn.com/sk.svg", alpha2: "SK", name: "Slovakia" },
    { dialCode: "+423", flag: "https://flagcdn.com/li.svg", alpha2: "LI", name: "Liechtenstein" },
    { dialCode: "+43", flag: "https://flagcdn.com/at.svg", alpha2: "AT", name: "Austria" },
    { dialCode: "+44", flag: "https://flagcdn.com/gb.svg", alpha2: "GB", name: "United Kingdom" },
    { dialCode: "+45", flag: "https://flagcdn.com/dk.svg", alpha2: "DK", name: "Denmark" },
    { dialCode: "+46", flag: "https://flagcdn.com/se.svg", alpha2: "SE", name: "Sweden" },
    { dialCode: "+47", flag: "https://flagcdn.com/no.svg", alpha2: "NO", name: "Norway" },
    { dialCode: "+48", flag: "https://flagcdn.com/pl.svg", alpha2: "PL", name: "Poland" },
    { dialCode: "+49", flag: "https://flagcdn.com/de.svg", alpha2: "DE", name: "Germany" },
    { dialCode: "+500", flag: "https://flagcdn.com/fk.svg", alpha2: "FK", name: "Falkland Islands" },
    { dialCode: "+501", flag: "https://flagcdn.com/bz.svg", alpha2: "BZ", name: "Belize" },
    { dialCode: "+502", flag: "https://flagcdn.com/gt.svg", alpha2: "GT", name: "Guatemala" },
    { dialCode: "+503", flag: "https://flagcdn.com/sv.svg", alpha2: "SV", name: "El Salvador" },
    { dialCode: "+504", flag: "https://flagcdn.com/hn.svg", alpha2: "HN", name: "Honduras" },
    { dialCode: "+505", flag: "https://flagcdn.com/ni.svg", alpha2: "NI", name: "Nicaragua" },
    { dialCode: "+506", flag: "https://flagcdn.com/cr.svg", alpha2: "CR", name: "Costa Rica" },
    { dialCode: "+507", flag: "https://flagcdn.com/pa.svg", alpha2: "PA", name: "Panama" },
    { dialCode: "+508", flag: "https://flagcdn.com/pm.svg", alpha2: "PM", name: "St. Pierre & Miquelon" },
    { dialCode: "+509", flag: "https://flagcdn.com/ht.svg", alpha2: "HT", name: "Haiti" },
    { dialCode: "+51", flag: "https://flagcdn.com/pe.svg", alpha2: "PE", name: "Peru" },
    { dialCode: "+52", flag: "https://flagcdn.com/mx.svg", alpha2: "MX", name: "Mexico" },
    { dialCode: "+53", flag: "https://flagcdn.com/cu.svg", alpha2: "CU", name: "Cuba" },
    { dialCode: "+54", flag: "https://flagcdn.com/ar.svg", alpha2: "AR", name: "Argentina" },
    { dialCode: "+55", flag: "https://flagcdn.com/br.svg", alpha2: "BR", name: "Brazil" },
    { dialCode: "+56", flag: "https://flagcdn.com/cl.svg", alpha2: "CL", name: "Chile" },
    { dialCode: "+57", flag: "https://flagcdn.com/co.svg", alpha2: "CO", name: "Colombia" },
    { dialCode: "+58", flag: "https://flagcdn.com/ve.svg", alpha2: "VE", name: "Venezuela" },
    { dialCode: "+590", flag: "https://flagcdn.com/gp.svg", alpha2: "GP", name: "Guadeloupe" },
    { dialCode: "+591", flag: "https://flagcdn.com/bo.svg", alpha2: "BO", name: "Bolivia" },
    { dialCode: "+592", flag: "https://flagcdn.com/gy.svg", alpha2: "GY", name: "Guyana" },
    { dialCode: "+593", flag: "https://flagcdn.com/ec.svg", alpha2: "EC", name: "Ecuador" },
    { dialCode: "+594", flag: "https://flagcdn.com/gf.svg", alpha2: "GF", name: "French Guiana" },
    { dialCode: "+595", flag: "https://flagcdn.com/py.svg", alpha2: "PY", name: "Paraguay" },
    { dialCode: "+596", flag: "https://flagcdn.com/mq.svg", alpha2: "MQ", name: "Martinique" },
    { dialCode: "+597", flag: "https://flagcdn.com/sr.svg", alpha2: "SR", name: "Suriname" },
    { dialCode: "+598", flag: "https://flagcdn.com/uy.svg", alpha2: "UY", name: "Uruguay" },
    { dialCode: "+599", flag: "https://flagcdn.com/bq.svg", alpha2: "BQ", name: "Bonaire" },
    { dialCode: "+60", flag: "https://flagcdn.com/my.svg", alpha2: "MY", name: "Malaysia" },
    { dialCode: "+61", flag: "https://flagcdn.com/au.svg", alpha2: "AU", name: "Australia" },
    { dialCode: "+62", flag: "https://flagcdn.com/id.svg", alpha2: "ID", name: "Indonesia" },
    { dialCode: "+63", flag: "https://flagcdn.com/ph.svg", alpha2: "PH", name: "Philippines" },
    { dialCode: "+64", flag: "https://flagcdn.com/nz.svg", alpha2: "NZ", name: "New Zealand" },
    { dialCode: "+65", flag: "https://flagcdn.com/sg.svg", alpha2: "SG", name: "Singapore" },
    { dialCode: "+66", flag: "https://flagcdn.com/th.svg", alpha2: "TH", name: "Thailand" },
    { dialCode: "+670", flag: "https://flagcdn.com/tl.svg", alpha2: "TL", name: "Timor-Leste" },
    { dialCode: "+672", flag: "https://flagcdn.com/nf.svg", alpha2: "NF", name: "Norfolk Island" },
    { dialCode: "+673", flag: "https://flagcdn.com/bn.svg", alpha2: "BN", name: "Brunei" },
    { dialCode: "+674", flag: "https://flagcdn.com/nr.svg", alpha2: "NR", name: "Nauru" },
    { dialCode: "+675", flag: "https://flagcdn.com/pg.svg", alpha2: "PG", name: "Papua New Guinea" },
    { dialCode: "+676", flag: "https://flagcdn.com/to.svg", alpha2: "TO", name: "Tonga" },
    { dialCode: "+677", flag: "https://flagcdn.com/sb.svg", alpha2: "SB", name: "Solomon Islands" },
    { dialCode: "+678", flag: "https://flagcdn.com/vu.svg", alpha2: "VU", name: "Vanuatu" },
    { dialCode: "+679", flag: "https://flagcdn.com/fj.svg", alpha2: "FJ", name: "Fiji" },
    { dialCode: "+680", flag: "https://flagcdn.com/pw.svg", alpha2: "PW", name: "Palau" },
    { dialCode: "+681", flag: "https://flagcdn.com/wf.svg", alpha2: "WF", name: "Wallis & Futuna" },
    { dialCode: "+682", flag: "https://flagcdn.com/ck.svg", alpha2: "CK", name: "Cook Islands" },
    { dialCode: "+683", flag: "https://flagcdn.com/nu.svg", alpha2: "NU", name: "Niue" },
    { dialCode: "+685", flag: "https://flagcdn.com/ws.svg", alpha2: "WS", name: "Samoa" },
    { dialCode: "+686", flag: "https://flagcdn.com/ki.svg", alpha2: "KI", name: "Kiribati" },
    { dialCode: "+687", flag: "https://flagcdn.com/nc.svg", alpha2: "NC", name: "New Caledonia" },
    { dialCode: "+688", flag: "https://flagcdn.com/tv.svg", alpha2: "TV", name: "Tuvalu" },
    { dialCode: "+689", flag: "https://flagcdn.com/pf.svg", alpha2: "PF", name: "French Polynesia" },
    { dialCode: "+690", flag: "https://flagcdn.com/tk.svg", alpha2: "TK", name: "Tokelau" },
    { dialCode: "+691", flag: "https://flagcdn.com/fm.svg", alpha2: "FM", name: "Micronesia" },
    { dialCode: "+692", flag: "https://flagcdn.com/mh.svg", alpha2: "MH", name: "Marshall Islands" }
];


export default countries;